#include "Instructor.h"




Instructor::Instructor()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:000000000000089A begin
{
}
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:000000000000089A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Instructor::Instructor(string n, string d, string g, int s)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:000000000000089C begin
{
}
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:000000000000089C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Instructor::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:00000000000008A2 begin
{
}
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:00000000000008A2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
