#include "Person.h"




Person::Person()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:0000000000000882 begin
{
}
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:0000000000000882 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Person::Person(string n, string d, string g)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:0000000000000887 begin
{
}
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:0000000000000887 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Person::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:000000000000088E begin
{
}
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:000000000000088E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
