#include "Student.h"




Student::Student()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:0000000000000890 begin
{
}
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:0000000000000890 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Student::Student(string n, string d, string g, string m)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:0000000000000892 begin
{
}
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:0000000000000892 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Student::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:0000000000000898 begin
{
}
// section -64--88-1--50-6e054084:15be9b87d5c:-8000:0000000000000898 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
